[from-internal]
; --- LLAMADAS INTERNAS CON BUZON ---
exten => _1XXX,1,NoOp(Llamada interna en curso hacia ${EXTEN})
same => n,Dial(PJSIP/${EXTEN},15,tT)
same => n,VoiceMail(${EXTEN}@default,u)
same => n,Hangup()

; --- ACCESO AL IVR NOVALINK ---
exten => 2000,1,Answer()
same => n,Goto(ivr-novalink,s,1)

; --- TRONCAL HACIA SEDE B ---
exten => _2XXX,1,NoOp(Llamada saliente hacia la sede remota por Troncal)
same => n,Dial(PJSIP/${EXTEN}@troncal-sede-b,60,tT)
same => n,Hangup()

; --- MUSICA EN ESPERA ---
exten => 2002,1,Answer()
exten => 2002,n,MusicOnHold()
exten => 2002,n,Hangup()

; --- REVISAR BUZON DE VOZ ---
exten => *97,1,Answer()
same => n,VoiceMailMain(${CALLERID(num)}@default)
same => n,Hangup()

; --- GRABADORA DE AUDIOS NOVALINK ---
exten => *77,1,Answer()
same => n,Record(/tmp/mensaje-novalink.wav)
same => n,Hangup()

; =========================================
; NUEVO CONTEXTO: MENU INTERACTIVO (IVR)
; =========================================
[ivr-novalink]
exten => s,1,NoOp(Entrando a la Operadora Automatica NovaLink)
same => n,Background(/tmp/mensaje-novalink)
same => n,WaitExten(5) ; Espera 5 segundos por una respuesta

; Opcion 1: Ventas (Ext. 1001)
exten => 1,1,Playback(digits/1)
same => n,Dial(PJSIP/1001,15)
same => n,VoiceMail(1001@default,u)
same => n,Hangup()

; Opcion 2: Soporte (Ext. 1002)
exten => 2,1,Playback(digits/2)
same => n,Dial(PJSIP/1002,15)
same => n,VoiceMail(1002@default,u)
same => n,Hangup()

; Opcion 3: Fátima (Ext. 1003)
exten => 3,1,Playback(digits/3)
same => n,Dial(PJSIP/1003,15)
same => n,VoiceMail(1003@default,u)
same => n,Hangup()

; Manejo de errores: Si marca un numero invalido
exten => i,1,Playback(pbx-invalid)
same => n,Goto(s,1)

; Manejo de errores: Si no marca nada y se acaba el tiempo
exten => t,1,Playback(vm-goodbye)
same => n,Hangup()