[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

; --- EXTENSION 1001 (ARTURO) ---
[1001]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=auth1001
aors=1001
rtp_timeout_hold=900

[auth1001]
type=auth
auth_type=userpass
password=secreto1001
username=1001

[1001]
type=aor
max_contacts=1

; --- EXTENSION 1002 (CRISTIAN) ---
[1002]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=auth1002
aors=1002
rtp_timeout_hold=900

[auth1002]
type=auth
auth_type=userpass
password=secreto1002
username=1002

[1002]
type=aor
max_contacts=1

; --- EXTENSION 1003 (FATIMA) ---
[1003]
type=endpoint
context=from-internal
disallow=all
allow=ulaw
allow=alaw
auth=auth1003
aors=1003
rtp_timeout_hold=900

[auth1003]
type=auth
auth_type=userpass
password=secreto1003
username=1003

[1003]
type=aor
max_contacts=1

; --- TRONCAL PJSIP HACIA SEDE B ---
[troncal-sede-b]
type=endpoint
transport=transport-udp
context=from-internal
disallow=all
allow=ulaw,alaw
aors=troncal-sede-b
direct_media=no

[troncal-sede-b]
type=aor
contact=sip:10.0.0.2:5060

[troncal-sede-b]
type=identify
endpoint=troncal-sede-b
match=10.0.0.2